# Generated by Django 3.2.5 on 2023-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.CharField(blank=True, max_length=30, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
